### ISSUE TITLE
Unable to select blender location, when it's installed via snap

### ISSUE THREAD

**Issue by nallath** [awiegel/CuraBlender#2]
I'm still on Fedora 28, so I installed blender 2.8 via snap. As such, the plugin is unable to find the location of blender.

When you open a .blend file, it asks for the location of blender. After pointing it to `/var/lib/snapd/snap/bin/blender` (which was the result of `where blender`), I see a message about it not being set correctly in the screen.

The logs say: 
```
2020-10-14 14:09:52,062 - ERROR - [Thread-4] CuraBlender.BLENDReader.read [57]: Exception: Problems with path to blender!
2020-10-14 14:09:52,063 - ERROR - [Thread-4] CuraBlender.BLENDReader.read [57]: NoneType: None
```

After this, the interface is frozen somehow. The resizing of the screen still works, so some parts are still being updated. But I cant close the window (apart from forcefully killing it) and none of the buttons seem to work.

I guess this is probably just some weirdness of my setup, since I understand that this isn't a very common way to use blender.

**Comment by awiegel** [comment]
This Plugin uses the Blender API (via the command line). The path to Blender gets verified by calling a simple command that checks the version of Blender.
I assume that something could be wrong with using Blender via snap and the command line.

Could you try executing this command in any shell (should return True):
"BLENDER_PATH" --background --python-expr "import bpy; print(bpy.app.version >= (2, 80, 0))"


If this is indeed the problem, I will try to find a workaround for installations via snap (if there is any).

Unfortunately I don't have any linux distribution atm to test this myself.

**Comment by nallath** [comment]
```
Blender 2.83.7 (hash 192e591af9fb built 2020-09-30 06:14:53)
Read prefs: /home/jaime/.config/blender/2.83/config/userpref.blend
/run/user/1000/snap.blender/gvfs/ non-existent directory
found bundled python: /var/lib/snapd/snap/blender/48/2.83/python
True

Blender quit
```

**Comment by awiegel** [comment]
Okay so this is working fine.

What if you set the path to Blender manually with the 'Debug Blenderpath' function. It's found under Extensions -> Cura Blender -> Debug Blenderpath.
There are two options available (file explorer and text field).

**Comment by nallath** [comment]
Both of them work. Weirdness. It could be because I did the text field option first.

**Comment by awiegel** [comment]
I also noticed random freezes when using the file explorer. I will observe this further.
