### ISSUE TITLE
"argument of type 'NoneType' is not iterable" in CuraBlender.CuraBlender._readMeshFinished

### ISSUE THREAD

**Issue by rburema** [awiegel/CuraBlender#3]
Hi!

We noticed some reports (11 unique users, on 17 occasions) have send a crash report for code that was within your plugin. You might want to take a look.

After checking if there'sn't any sensitive information in there, I've made the following issue public, so you can investigate:
https://sentry.io/share/issue/eff71a744ce84131a550264c9b6ba04a/

cheers,
Remco, Cura-team.

**Comment by awiegel** [comment]
Hey!

Thank you for submitting this crash report to me.

Unfortunately I was not able to reproduce this crash in any way.
Nevertheless I added some error handling, so a crash should not happen in any case.

Feel free to contact me again, when crashes occur on the next release (1.0.1).

All the best
Alex
