### ISSUE TITLE
mime_type error when saving to removable drive with Dremel3D20 plugin installed

### ISSUE THREAD

**Issue by timmehtimmeh** [awiegel/CuraBlender#4]
Hi -

I'm the author of the [Dremel3D20 plugin](https://github.com/timmehtimmeh/Cura-Dremel-3D20-Plugin), and I've been chasing down [an issue that one of my users reported.](https://github.com/timmehtimmeh/Cura-Dremel-3D20-Plugin/issues/72) 

It seems that there's a mime_type error that comes up if a user has both of our plugins installed.  I've been able to reproduce the issue with the following steps

1. Install Cura 4.8
2. Install the Dremel3D20 plugin from the marketplace
3. Install the CuraBlender plugin from the marketplace
4. Add a Dremel3D20 printer & set the Dremel3D20 up as the active printer
5. Import a 3d model (i.e. benchy)
6. Slice the model
7. Click "Save to removable drive"

After doing the above steps it appears that Cura produces a "mime_type" error and no file is saved out.
![image](https://user-images.githubusercontent.com/19733103/108607442-64890000-7375-11eb-9806-563a11129c62.png)

I believe this is because both of our plugins implement a mesh_writer type - with the Dremel3D20 producing .g3drem files, and yours producing .blend files.

After a bit more investigation/testing I think there's an easy one-line fix .  If I edit the CuraBlender's __init__.py to add the following line into the mesh_writer section:

```"mime_type": "application/x-blender",```

then reload Cura then I can successfully save the .g3drem file when I select "Save to removable drive"
![image](https://user-images.githubusercontent.com/19733103/108607583-16c0c780-7376-11eb-9e5b-5be0a541397b.png)

Note - I don't have Blender installed, and haven't tested that this doesn't break your plugin (although I'd be surprised if it does), which is why i'm not making a pull request.

I've pasted the contents of the __init__.py that works for me below:

Cheers!
Tim

```
# Imports from Uranium.
from UM.Mesh.MeshWriter import MeshWriter # For the binary mode flag.

# Imports from own package.
from . import CuraBlender, BLENDReader, BLENDWriter


def getMetaData():
    """Initialization of the plugin."""

    return {
        'type': 'extension',
        'mesh_reader': [
            {
                'extension': 'blend',
                'description': CuraBlender.catalog.i18nc('@item:inlistbox', 'BLEND File')
            }
        ],
        'mesh_writer': {
            "output": [
                {
                    "mode": MeshWriter.OutputMode.BinaryMode,
                    "extension": "blend",
                    "mime_type": "application/x-blender",
                    "description": CuraBlender.catalog.i18nc("@item:inlistbox", "BLEND File")
                }
            ]
        }
    }


def register(app):
    """Registers the plugin in cura on start."""

    return {
            'extension': CuraBlender.CuraBlender(),
            'mesh_reader': BLENDReader.BLENDReader(),
            'mesh_writer': BLENDWriter.BLENDWriter()
            }
```

**Comment by awiegel** [comment]
Hey Tim!

Your suggested fix perfectly solved this problem!
An update should be released in the next days.

Cheers and thanks for the effort!
Alex

**Comment by timmehtimmeh** [comment]
Thanks for the quick fix Alexander 🎉 
Cheers!
