### ISSUE TITLE
Cannot open Blender files

### ISSUE THREAD

**Issue by Montezuma-69** [awiegel/CuraBlender#5]
Blender 2.90 and 2.91, Cura 4.8.0, Windows 10 20H2
When i open a .blender file, following message appears:
Filed to load c:\temp\y-sensor-traeger.blend. The file could be corrupe or inaccessible.

Blender path is set to C:\Program Files\Blender Foundation\Blender 2.91\blender.exe

**Comment by awiegel** [comment]
This plugin converts _.blend_ files internally into another file format which can be changed under:
Extensions -> CuraBlender -> Settings.

Note that some _.blend_ files might be **too complex** to be converted into those file formats.

Have you tried it with other .blend files or changing the file extension?

**Comment by Montezuma-69** [comment]
Thank you, yes, ive tried different files. 
Ive found a hint now:
If i followiyour installation description:
> To install this plugin, simply drag this folder unzipped into your plugins folder.
then it doesnt work. If i register to marketplace and install from there, it works well.

**Comment by awiegel** [comment]
Well I should probably change the installation description, good hint!
I'm glad that it works now. ;)
