### ISSUE TITLE
open specific mesh, not the complete blender file

### ISSUE THREAD

**Issue by rooiejoris** [awiegel/CuraBlender#6]
Hi,

Just found your plugin (haven't tried it yet, but looks promising!).
In my workflow I have multiple meshes in one blender file.
Is it possible to select a specific mesh? (or in the future?). Can't see that in the trailer video.
(maybe very clear after using, but are the modifiers applied before importing?)

cheers / joris

**Comment by awiegel** [comment]
Hey,

in Blender, it should be possible to set specific meshes as inactive/invisible.
Only active/visible meshes should be loaded by this plugin.

Let me know if this works for you.

Cheers
Alex

**Comment by rooiejoris** [comment]
Just quickly tried, but it seems it doesn't import anything at the moment.
Runing MacOS 10.14.6, maybe that's the problem. I read it somewhere with a (or anoher?!) blender plugin in cura.
Also using multiple blender versions, so maybe I used a wrong path. Will test it again, but now working on other things... : )

cheers / joris

**Comment by awiegel** [comment]
If you haven't tried already, you can try to set the path to Blender manually with the 'Debug Blenderpath' function.
It's found under Extensions -> Cura Blender -> Debug Blenderpath.

Note that Blender version 2.80 or higher is required.

Cheers
Alex
